name: setup-firebase-tools
branding:
  icon: 'package'
  color: 'gray-dark'
description:
  Install firebase tools
  This action is required node.
  If you want to install node, please use actions/setup-node@v4.
  Also this action is supported node that installed by other way.
inputs:
  googleApplicationCredentialsContents:
    required: true
    description: |
      google application credential file.
      allowed base64 encoded or just plain text.
      if put base64 encoded contents, Please set encode option.
  encode:
    required: false
    default: 'utf8'
    description: |
      define GOOGLE_APPLICATION_CREDENTIALS_CONTENT encode.
      you can use `utf8` or `base64`.
      default value is `utf8`.
  credentialPath:
    required: false
    default: ${{runner.temp}}/googleApplocationCredentials.json
    description: |
      default credential path is `${{runner.temp}}/googleApplocationCredentials.json`
      if you want to override, plz set.
runs:
  using: composite
  steps:
    - name: firebase cli
      shell: bash
      run: |
        curl -sL https://firebase.tools | bash

    - name: save GOOGLE_APPLICATION_CREDENTIALS file
      uses: joutvhu/write-file@v1
      with:
        path: ${{ inputs.credentialPath }}
        contents: ${{ inputs.googleApplicationCredentialsContents }}
        write_mode: overwrite
        encoding: ${{ inputs.encode }}

    - name: set keys
      shell: bash
      run: |
        echo "GOOGLE_APPLICATION_CREDENTIALS=${{inputs.credentialPath}}" >> $GITHUB_ENV
        
