name: setup firebase tools with credentials file
branding:
  icon: 'package'
  color: 'gray-dark'
description:
  Install firebase tools
  This action is required node.
inputs:
  firebaseToolsVersion:
    required: false
    default: '13.33.0'
    description: 'firebase tools version'
  googleApplicationCredentialsContents:
    required: true
    description: |
      google application credential file.
      allowed base64 encoded or just plain text.
      if put base64 encoded contents, Please set encode option.
  encode:
    required: false
    default: 'utf8'
    description: |
      define GOOGLE_APPLICATION_CREDENTIALS_CONTENT encode.
      you can use `utf8` or `base64`.
      default value is `utf8`.
  credentialPath:
    required: false
    default: default
    description: |
      default credential path is `\$\{\{runner.temp\}\}/googleApplocationCredentials.json`
      if you want to override, plz set.
runs:
  using: composite
  steps:
    - name: firebase cli
      shell: bash
      run: |
        npm install -g firebase-tools@${{ inputs.firebaseToolsVersion }}

    - name: credential path
      shell: bash
      run: |
        if [ "${{inputs.credentialPath}}" -eq "default" ]; then
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{runner.temp}}/googleApplocationCredentials.json" >> $GITHUB_ENV
        else
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{inputs.credentialPath}}" >> $GITHUB_ENV
        fi
        

    - name: save GOOGLE_APPLICATION_CREDENTIALS file
      uses: joutvhu/write-file@v1
      with:
        path: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        contents: ${{ inputs.googleApplicationCredentialsContents }}
        write_mode: overwrite
        encoding: ${{ inputs.encode }}

        
